#version 450

// LoRA Expand Forward: delta_k = B @ c_k for each branch
//
// B is a shared basis matrix [vsa_dim, rank] (persistent, learned)
// c is per-branch coefficients [batch, K, rank] (generated by hypernetwork)
// Output: predictions [batch, K, vsa_dim]

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

// Shared LoRA basis: [vsa_dim, rank] stored row-major
layout(set = 0, binding = 0) readonly buffer Basis {
    float B[];
};

// Coefficients from hypernetwork: [batch, K * rank]
layout(set = 0, binding = 1) readonly buffer Coefficients {
    float coeffs[];
};

// Output predictions: [batch, K, vsa_dim]
layout(set = 0, binding = 2) writeonly buffer Predictions {
    float preds[];
};

layout(push_constant) uniform PushConsts {
    uint batch_size;
    uint K;
    uint D;         // vsa_dim
    uint rank;
};

void main() {
    uint batch_idx = gl_WorkGroupID.y;
    uint k = gl_WorkGroupID.z;
    uint tid = gl_GlobalInvocationID.x;

    if (tid >= D || k >= K) return;

    // c_k = coeffs[batch_idx * K * rank + k * rank .. + rank]
    uint coeff_base = batch_idx * K * rank + k * rank;

    // delta_k[tid] = sum_r(B[tid * rank + r] * c_k[r])
    float sum = 0.0;
    for (uint r = 0; r < rank; ++r) {
        sum += B[tid * rank + r] * coeffs[coeff_base + r];
    }

    uint pred_idx = (batch_idx * K + k) * D + tid;
    preds[pred_idx] = sum;
}
